# Generated by Django 4.1.2 on 2022-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_hotel_alter_restaurant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(to='app.food_iteams'),
        ),
    ]
