# Generated by Django 4.1.2 on 2022-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_meals_order_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
