# Generated by Django 4.1.2 on 2022-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'delivery'), (1, 'cooking'), (2, 'on_the_way'), (3, 'cancel')], default=1),
        ),
    ]
