# Generated by Django 4.1.2 on 2022-11-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'cooking'), (2, 'on_the_way'), (3, 'cancel'), (4, 'delivered')], default=1),
        ),
    ]
