# Generated by Django 4.1.2 on 2022-11-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
