# Generated by Django 4.1.2 on 2022-11-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
