# Generated by Django 4.1.2 on 2022-11-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.food_iteams'),
        ),
    ]
