# Generated by Django 4.1.2 on 2022-11-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(to='app.food_iteams'),
        ),
    ]
