# Generated by Django 4.1.2 on 2022-11-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_quantity_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
